### ISSUE TITLE
OLS vis expand window button doesn't work

### ISSUE THREAD

**Issue by jmcmurry** [EBISPOT/OLS#108]
[On the graph viz page](http://www.ebi.ac.uk/ols/ontologies/hp/terms/graph?iri=http://purl.obolibrary.org/obo/HP_0009381&&ed=http://purl.obolibrary.org/obo/HP_0009381&&http://purl.obolibrary.org/obo/HP_0005922&&http://purl.obolibrary.org/obo/HP_0006265&&http://purl.obolibrary.org/obo/HP_0001155&&), there's an icon which seems to indicate that you can maximize the window (not just zoom); this appears not to work, at least on chrome over mac osx.

This maximize feature would be particularly useful when there are lots of nodes that need to be seen at one time. Fonts are just too small for humans.

<img width="594" alt="screen shot 2016-08-09 at 4 50 51 pm" src="https://cloud.githubusercontent.com/assets/3658863/17537446/8ce46ca8-5e51-11e6-9079-ed2a6eec094a.png">

As a side comment, I would recommend doing away with displaying the IDs (instead showing those on hover). That would allow you to increase the font size without cluttering the window with text.

**Comment by LLTommy** [comment]
Hi, 
the functionality of the button is to 'fit' the nodes to window - so if you zoom in for example and click on it, it will zoom out so every node is visible. I am sorry if it gives the impression to be able to go to a full screen mode - we could replace the icon with a different one - but in anyway there is no functionality for full screen mode, so there is nothing broken here. 

About displaying the IDs - I show them, because some people explicitly asked for it! Anyway, to be flexible I included this as an option. Find the two checkboxes on the right hand side below the 'Get permalink to this graph' button,  - namely 'Show label' and 'Show id'. The default is to show both, but you can adjust it to just show the labels or just show the ids. 

The font size could be adjusted, but It is kind of hard to find the right size for all cases (only a few nodes, many nodes, long labels, short labels) as well as different screen sizes. Maybe I could include an option to dynamically increase/decrease the font size, that probably would be useful. Anyway, the easiest way to adjust the font size right away to your individual settings is to simply press ctrl and + and zoom in a bit with your browser - you can almost simulate a full screen mode like that.

**Comment by jmcmurry** [comment]
Heh; well you can't please everyone. :) Do consider making it possible to maximize the screen. Then you wouldn't have to futz with the font size or remove labels. You'd be able to zoom in sensibly to whatever the user is comfortable with and still see more than one of the node clusters at a time.
