### ISSUE TITLE
dbxref provenance not clear

### ISSUE THREAD

**Issue by jmcmurry** [EBISPOT/OLS#201]
Looking at the dbxref section of a page like [this](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_98249):  I'm not quite sure what the source of the XRef designation "exact" is, whether automated on the part of OLS (via text mining or equivalent), or whether it is directly from orphanet/ordo.

ps, the text "database xref" is [hyperlinked](https://www.ebi.ac.uk/ols/search?q=database_cross_reference&exact=true&type=property&ontology=ordo) to no avail. Hyperlink could be removed, but it would be great if instead this page instead were a static documentation about how these xrefs are sourced. Alternatively, if this hyperlink is meant to convey something in particular, what that is isn't clear to me. I may just be too sleepy/dense.

<img width="876" alt="screen shot 2018-04-11 at 1 38 23 am" src="https://user-images.githubusercontent.com/3658863/38605758-170fc442-3d29-11e8-9dd6-ae147eee4513.png">

cc: @cmungall

**Comment by simonjupp** [comment]
In this case the hasDbXref is the original annotation in the ontology. OLS processes xrefs into a new database_cross_reference annotation and does additional formatting (like showing the axiom annotations and hyperlinking where it can). This is why you see two at the moment and the database_cross_reference is made up by OLS which is why you get no hits in the search - we probably shouldn't hyperlink this. 

We're currently updating OLS to integrate with OxO for showing xrefs so there will be some changes to how these xrefs are displayed in OLS. Thanks for the comment!
