### ISSUE TITLE
Search on OLS

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#25]
I'm trying to search OLS for "pharynx". From the home page, I get a few suggestions, but I was hoping for the Wormbase (WBbt) term which doesn't show up. If I go to http://www.ebi.ac.uk/ols/beta/ontologies/wbbt and search for "pharynx" it does show up.

Is there a limit on the number of results from the home page? If yes, maybe consider having an indication along the lines of "5 more results" as an hyperlink to display the rest of the results?

**Comment by tonysawfordebi** [comment]
Searching using the REST API doesn't find anything either:
http://www.ebi.ac.uk/ols/beta/api/search?ontology=wbbt&local=true&q=pharynx returns 0 hits

**Comment by simonjupp** [comment]
If you just search by pressing enter (without picking a suggestion) you go through to the full search results. You can then filter specifically on wbbt. 

e.g. http://www.ebi.ac.uk/ols/beta/search?q=pharynx&start=0&ontology=wbbt

As for it not coming back in the API, it's because OLS hasn't detected the local terms for WBBT correctly. Change local=flase and it works. This will be because they've used a specific casing pattern for WBBT ids that I was't aware. I'll update the config file for that. Thanks

**Comment by mcourtot** [comment]
Maybe add a "press enter for full results" at the bottom of the dropdown? As is it seems those are the only results the user would get, it's not clear the list is cut. Thanks!
