### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by bistline** [EBISPOT/OLS#313]
We are getting ready to release a new service for our web application that will call OLS to validate various ontology terms that are read from a user-uploaded metadata file.  So far, everything has worked fine, but we noticed late last week that some of our integration tests were failing intermittently when trying to ingest data.  Inspection of the logs indicated that some calls to OLS failed to connect when attempting to look up terms in the cell ontology (CL).  This was the exception we saw in our logs (from the Python ETL pipeline that calls OLS):

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.ebi.ac.uk', port=443): Max retries exceeded with url: /ols/api/ontologies/cl 
(Caused by NewConnectionError('curllib3.connection.VerifiedHTTPSConnection object at 0x7f7573495c18\\u003e: Failed to establish a new connection: [Errno 110] Connection timed out`

My question is this - were there any service outages late last week (specifically 2020-01-09 3-4:30PM EDST and 2020-01-10 3-6PM, EST)?  If not, does OLS employ any kind of rate limiting/throttling on connections if we attempt too many queries in a given timeframe?  

We will be using this in a production context soon, so we would like to know if there are any best practices for using OLS in terms of number of requests/timeouts, etc.  Thanks.

**Comment by henrietteharmse** [comment]
This problem is typical where any TCP/IP network point gets flooded with requests to the point that the backlog for the socket in question is filled up. At that point you can experience a variety of network related errors. For example, you may start receiving timeouts which later may be followed by connection refused errors. 

These errors are TCP/IP errors and are not (OLS) application specific. In particular, OLS does not employ any throttling or limiting of any sort. However, for any server, it is given that the server has limited resources, which in this case means the server can only allow a limited number of concurrent connections. 

The question now is, how can one deal with this? There are 2 main strategies:
(1) Do not call a service repeatedly without some delay between subsequent calls. In Python this can be achieved using a sleep().
(2) When network exceptions start to happen an exponential back-off is customary. For more info on exponential back-off see https://en.wikipedia.org/wiki/Exponential_backoff. In Python this can be achieved for example by using https://pypi.org/project/backoff/.

**Comment by bistline** [comment]
Thanks for the quick response - I hadn't considered that this would be happening on our end, and not at the requested resource.  We do exponential backoffs in other places (when calling various Google APIs) but haven't implemented that in this codebase.  We'll take a look at doing that, in addition to trying to throttle the rate of requests on our end when calling OLS.  I'll close this now as it looks like the issue is on our end.
