### ISSUE TITLE
Old version of UBERON in OLS?

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OLS#320]
Hi,

The current UBERON version in OLS (https://www.ebi.ac.uk/ols/ontologies/uberon) says
Version: 2018-11-25
Last loaded: Tue Jan 21 06:24:45 GMT 2020 

But a more recent version was released 3 months ago (see http://uberon.github.io/ and http://www.ontobee.org/ontology/UBERON). I thought we already had that recent version in OLS, but anyway, could you please force an update? 

Thanks,
Paola

**Comment by henrietteharmse** [comment]
I did do a force but it did not update the version of uberon because its IRI points to http://purl.obolibrary.org/obo/uberon.owl which resolves to http://ontologies.berkeleybop.org/uberon.owl which refers to `<owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/uberon/releases/2018-11-25/uberon.owl"/>`. 

Uberon in OLS will reflect the new version once their IRI (http://purl.obolibrary.org/obo/uberon.owl) points to the latest version.

**Comment by matentzn** [comment]
Wowwww maaaaan @henrietteharmse you are right! This should not be the case..

**Comment by matentzn** [comment]
Taking care of this.

**Comment by matentzn** [comment]
Ok the Uberon purl is fixed now; OLS has not updated yet, but I guess it will when your development cycle closes..

**Comment by henrietteharmse** [comment]
The 2019-11-22 version of Uberon is now available in OLS.

**Comment by matentzn** [comment]
Amazing thanks @henrietteharmse Closing this now :)
