### ISSUE TITLE
ECTO is empty

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#321]
https://www.ebi.ac.uk/ols/ontologies/ecto

no classes... cc @matentzn

**Comment by matentzn** [comment]
Its true @henrietteharmse The purl seems to be false:

http://purl.obolibrary.org/obo/ecto

should be

http://purl.obolibrary.org/obo/ecto.owl

**Comment by henrietteharmse** [comment]
The OLS load of ECTO failed due to a parsing error. To test this I tried to open ECTO in Protege 4.3 (because that corresponds to the OWL API version used in OLS) and it gives this error:

`org.semanticweb.owlapi.rdf.syntax.RDFParserException: [line=1988:column=137] IRI 'http://www.geneontology.org/formats/oboInOwl#http://www.geneontology.org/formats/oboInOWL#xref' cannot be resolved against curent base IRI http://purl.obolibrary.org/obo/ecto.owl`.

which refers to this line:

 `<owl:AnnotationProperty rdf:about="http://www.geneontology.org/formats/oboInOwl#http://www.geneontology.org/formats/oboInOWL#xref"/>`

**Comment by matentzn** [comment]
Ok, this is a problem with EXO. There is not much we can do other than hacking, which I will do in ECTO itself. To fix it properly, this needs to be fixed:

https://github.com/CTDbase/exposure-ontology/issues/11

I am taking care of this ticket, thanks all.

**Comment by henrietteharmse** [comment]
ECTO is no longer empty: https://www.ebi.ac.uk/ols/ontologies/ecto

**Comment by matentzn** [comment]
An with my new favourite term @diatomsRcool I am closing the issue. https://www.ebi.ac.uk/ols/ontologies/ecto/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECTO_0800001&viewMode=All&siblings=true

**Comment by matentzn** [comment]
THANKS @henrietteharmse for all!
