### ISSUE TITLE
Feature request: Support Property Hierarchies in hierarchical views

### ISSUE THREAD

**Issue by jmcmurry** [EBISPOT/OLS#325]
[In OLS, the RO terms](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_HOM0000069&viewMode=All&siblings=false) are showing up at the top level like so:

<img width="698" alt="Screen Shot 2020-02-21 at 10 41 57 AM" src="https://user-images.githubusercontent.com/3658863/75062039-d397f400-5496-11ea-8d93-fd276ba4eab3.png">

whereas the subproperty should be driving the hierarchy like so: 

<img width="881" alt="Screen Shot 2020-02-21 at 10 36 26 AM" src="https://user-images.githubusercontent.com/3658863/75061786-510f3480-5496-11ea-9696-00adecd5a6aa.png">

cc: @cmungall

**Comment by henrietteharmse** [comment]
I tried to have a look at RO in Protege 4.3 (because it uses the OWL API that corresponds to the 1 in OLS) but I get the following error:

![image](https://user-images.githubusercontent.com/32327979/75143439-f3285a00-56ec-11ea-8137-ffec4fa5b8b6.png)

I suspect it results in the ontology loading partially.

**Comment by matentzn** [comment]
This seems like a very important issue. This has two aspects to it:
1) OLS needs to upgrade to a later OWL API version. This is such as major thing, it will probably take a long while to happen. Every curator using Protege, ROBOT, ODK and so on is long since on a much newer version of OWL API, so we would not ever notice problems that cause parsing errors in an older version of the OWL API!

2) We absolutely need RO to be browsable. Proposed solution below:

@henrietteharmse can you try to open 
http://purl.obolibrary.org/obo/ro/ro-base.owl

If this works for you, consider switching the location of RO to that one for now, but give @cmungall or @dosumis 2 days to object. The next step would be to add this ticket to the OWL API upgrade milestone.

**Comment by henrietteharmse** [comment]
http://purl.obolibrary.org/obo/ro/ro-base.owl seems to work.

**Comment by matentzn** [comment]
Thanks @henrietteharmse! @dosumis @cmungall if you dont object, we will switch to ro-base on Wednesday.

**Comment by henrietteharmse** [comment]
I made a wrong assumption here. Usually when an ontology does not load via Protege 4.3 it will not load via OLS. In this instance, this is not the case. I loads fine in OLS. What I suspect is that the property hierarchy is not properly populated.

**Comment by cmungall** [comment]
I'm not massively keen on this as we'll end up with lots of root floaters?

Try ro.obo?

**Comment by matentzn** [comment]
To be clear, it appears that OLS never fully (or at all) supported role hierarchies.. Switching to another serialisation wont help (@simonjupp); I would recommend closing this ticket and making a new one: "Feature request: Support Property Hierarchies in hierarchical views" and throw it on the heap of mid term priorities..

**Comment by jmcmurry** [comment]
To maintain continuity, I've just renamed this issue rather than close/reopen.

**Comment by simonjupp** [comment]
Definitely something strange happening. Some of the object property hierarchy is rendering correctly

 https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002378&viewMode=All&siblings=false

**Comment by matentzn** [comment]
the only thing that springs to mind is that imported ontologies are ignored.

**Comment by simonjupp** [comment]
The imported files are not ignored but when we index the ontology we're only looking for super properties in the active ontology, and not looking in all the imported ontologies. The offending bit of code is  [here]( https://github.com/EBISPOT/OLS/blob/a3034688408cdc499b9220e72371779a347002ed/ontology-tools/src/main/java/uk/ac/ebi/spot/ols/loader/AbstractOWLOntologyLoader.java#L722) @henrietteharmse . 

For classes we use the reasoner to get superclasses, which avoids having to worry about the imported ontologies. You could in theory do the same with `getSuperObjectProperties`, but note this isn't supported by the version of ELK we are using. The simplest fix is to just make sure you look in all the imported ontologies.

**Comment by henrietteharmse** [comment]
@jmcmurry I think this is working now:

![image](https://user-images.githubusercontent.com/32327979/75903748-ee288080-5e39-11ea-9da4-85978014d46c.png)
