### ISSUE TITLE
Refresh MP

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#330]
For some reason, https://www.ebi.ac.uk/ols/ontologies/mp seems to be still an old version, at least from the looks of it (there have been at least 3 releases since November). Is it possible to  to refresh? Also, do we know yet what the criteria are for OLS not refreshing ontologies in the overnight data load? Does it differ from ontology to ontology?

**Comment by henrietteharmse** [comment]
The way OLS determines whether to update an ontology or not is it will always download the new file. To determine whether the new file will be used to re-index the ontology, a SHA1 checksum is calculated on the file. If the checksum for the new file matches that of the previous, it assumes the file has not changed. 

It is possible that different inputs can result in the same SHA1 digest being generated. I think that is what has happened here, hence the reason why mp was not updated. We should consider using a SHA2/3 checksum rather.

I think in the meantime we can force this update once the DC move is over.

**Comment by udp** [comment]
I think the issue was not a hash collision (as this is practically impossible) but rather that the "latest" hash was updated BEFORE the ontology was successfully loaded.  So if something bad happened while the ontology was loading, the hash file would still indicate that the latest version had been loaded.  I have hopefully fixed this now by storing a hash of the version that is loaded in the database, AFTER loading.
