### ISSUE TITLE
Update of PRIDE ontology is not happening

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#331]
https://github.com/PRIDE-Utilities/pride-ontology/blob/master/pride_cv.obo

**Comment by henrietteharmse** [comment]
This is due to the DC move. Please open a ticket if PRIDE is still not updated once OLS has done an update after the DC move.

**Comment by ypriverol** [comment]
Update of PRIDE ontology is not happening again. Is this process nightly-based.

**Comment by henrietteharmse** [comment]
Further showed that the reason why PRIDE is not happening is because there is a problem with the .obo file. 

It gives the following error: 
`org.xml.sax.SAXParseException; systemId: https://raw.githubusercontent.com/PRIDE-Utilities/pride-ontology/master/pride_cv.obo; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.`

In general, if you cannot open an ontology in Protege 4.3, it will not load in OLS. Though, in this case PRIDE also does not load using Protege 5.5 either.

I was wondering why we are loading a .obo file rather than a .owl file for PRIDE? In general the preference is to use .owl files.

**Comment by ypriverol** [comment]
which client do you use? we have been updating the obo so far. If we can continue with that it would be great. Let me know the client you are using to test in our side.

**Comment by henrietteharmse** [comment]
Protege is the client we use.

**Comment by ypriverol** [comment]
Thanks, I used another client and everything was fine. I now user Protege and fixed the error. It should be fine now.

**Comment by henrietteharmse** [comment]
PRIDE has been successfully updated on OLS.
