### ISSUE TITLE
Documentation of responses

### ISSUE THREAD

**Issue by lgatto** [EBISPOT/OLS#34]
Where can I read more about the different fields of the responses. For example, what's the `version` of an ontology, and how does it differ from the `config/version`.

**Comment by simonjupp** [comment]
The config/version is the ontology version. If the ontology contains a version number in the metadata then that will be used, otherwise we will use the date we loaded it as the version. 

I think the other version field should be ignored, it seems to be null for all ontologies and just needs to be removed.

**Comment by lgatto** [comment]
Thanks. Is there a resources that describes all these fields in more details?

**Comment by LLTommy** [comment]
Sorry, not yet - after all we are still in beta :) and smaller changes to the structure might happen  - but we might put something together in the near future if it is useful for people.

**Comment by lgatto** [comment]
Great, thank you very much.
