### ISSUE TITLE
Search API returns incorrect synonyms for CHEBI_17544 matches

### ISSUE THREAD

**Issue by turbomam** [EBISPOT/OLS#349]
CHEBI_17544, 'hydrogencarbonate ' when viewed at the ChEBI website or the [OLS web interface](https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_17544) has 'bicarbonate' as a synonym.

I have submitted 'bicarbonate' to the search API with R. See code and results below.

**For CHEBI_17544, I consider**
- 'hydrogen(trioxidocarbonate)(1-)' a false positive 
- 'bicarbonate' a false negative

```R
temp <-
  httr::GET(
    paste0(
      'http://www.ebi.ac.uk/ols/api/search?q=',
      '{bicarbonate}&ontology=chebi&fieldList=short_form,label,synonym'
    )
  )
temp <- jsonlite::fromJSON(rawToChar(temp$content))
temp <- temp$response$docs
print(temp$synonym[temp$short_form == 'CHEBI_17544'])
```

>[[1]]
[1] "hydrogencarbonate(1-)"           "hydrogen(trioxidocarbonate)(1-)" "hydroxidodioxidocarbonate(1-)"   "Hydrogencarbonate"              
[5] "hydrogencarbonate"               "hydrogentrioxocarbonate(IV)"     "hydrogentrioxocarbonate(1-)"

**Comment by udp** [comment]
CHEBI_17544 has hydrogen(trioxidocarbonate)(1−) listed as on of its IUPAC names - see for example https://www.ebi.ac.uk/chebi/searchId.do?chebiId=17544. Therefore, it is not a false positive as far as OLS is concerned.

"Bicarbonate" does not show up in the synonyms list because it is a "hasRelatedSynonym" relation in the ChEBI ontology, and OLS currently only includes "hasExactSynonym" relations in the synonym list for ChEBI.  It is still present as an annotation, however.  You can see it in your query results by adding annotations_trimmed to the fieldList.

**Comment by turbomam** [comment]
This is very helpful. Apologies for the false positive accusation!
