### ISSUE TITLE
Does exact parameter in search API work?

### ISSUE THREAD

**Issue by turbomam** [EBISPOT/OLS#350]
This search is fruitful:
https://www.ebi.ac.uk/ols/api/search?q={hydrogencarbonate}

Searching for 'hydrogencarbonate' in the web interface and ticking the exact button also works. The URL that appears in the navigation bar is 
https://www.ebi.ac.uk/ols/search?q=hydrogencarbonate&groupField=iri&exact=on&start=0

But none of these REST calls return anything:

- https://www.ebi.ac.uk/ols/api/search?q={hydrogencarbonate}&exact=true
- https://www.ebi.ac.uk/ols/api/search?q={hydrogencarbonate}&exact=True
- https://www.ebi.ac.uk/ols/api/search?q={hydrogencarbonate}&exact=TRUE
- https://www.ebi.ac.uk/ols/api/search?q={hydrogencarbonate}&exact=1
- https://www.ebi.ac.uk/ols/api/search?q={hydrogencarbonate}&exact=on

**Comment by LLTommy** [comment]
Hey,
well what happens here is that you ask for fuzzy label match for "{hydrogencarbonate}" and you get some hits because it's almost "hydrogencarbonate". When you turn on exact label match, you don't get anything anymore which makes sense. So, basically, what you want is:
-  https://www.ebi.ac.uk/ols/api/search?q=hydrogencarbonate&exact=true

**Comment by turbomam** [comment]
Thanks! That is so embarrassing. :-(
