### ISSUE TITLE
Individuals

### ISSUE THREAD

**Issue by lgatto** [EBISPOT/OLS#37]
I struggle a bit with individuals. They seem to be images, as in the `ceph` ontolgy

```
http://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Nautilus_pompilius_%28head%29.jpg/240px-Nautilus_pompilius_%28head%29.jpg
```

or comments/annotations about terms, as in the `ncro` ontology (these are the labels)

```
 [1] "failed exploratory term"                   
 [2] "pending final vetting"                     
 [3] "core"                                      
 [4] "to be replaced with external ontology term"
 [5] "placeholder removed"                       
 [6] "terms merged"                              
 [7] "organizational term"                       
 [8] "ready for release"                         
 [9] "defined class"                             
[10] "metadata incomplete"                       
[11] "example to be eventually removed"          
[12] "named class expression"                    
[13] "universal"                                 
[14] "uncurated"                                 
[15] "metadata complete"                         
[16] "term imported"                             
[17] "term split"                                
[18] "requires discussion"        
```

I can find the number of individuals in an ontology, I can download all the individual in an ontology, but I can't link any of these individual to a term. 

Could somebody explain what an *individual* is and how to a terms individual?

**Comment by simonjupp** [comment]
Individuals are members of classes. In this example you've found some references to a specific individual but there is no type information, but it may have been referenced in a different way (from a relationship in annotation on a term). There are probably a lot of individuals in OLS that aren't typed.

**Comment by lgatto** [comment]
> Individuals are members of classes

What's a class in the frame on ontologies? What is a types/untyped individual? 

> ... it may have been referenced in a different way (from a relationship in annotation on a term).

If I checked all the properties (relations) and all the terms in an ontology, would I find these individuals? Where, in what field?

**Comment by simonjupp** [comment]
In OWL we talk about classes or concepts rather than terms, but in OLS term
and class mean the same thing. Phil Lord wrote a useful short article on
the difference between classes and individuals here.
http://ontogenesis.knowledgeblog.org/514

Any individual OLS finds asserted in an OWL file is indexed and made
available via the API under api/{ontoname}/individuals. These individuals
might have a type that links to a term, but I haven't yet exposed the
inverse relation in the API (but I will). When this is done terms will have
an "individuals" link that gets you to any individuals of that term.

In addition to typing, a term might also be related in some other way to an
individual. e.g. termX hasImage <http://www.example/someimage.jpg>. These
aren't currently being indexed either so you can't get these properties
from the API. What I suspect you have been seeing is individuals appearing,
like http://www.example/someimage.jpg, that aren't related to anything.

Dealing with individuals has been a lower priority because they aren't
heavily used by most ontologies. I will try and do some work on the backend
to improve this.

**Comment by lgatto** [comment]
Thanks, @simonjupp, I will do a bit of background reading. 

I can see that individuals are not a priority. I think I won't provide any explicit interface at the R level either, at least at this stage. I will expand this functionality later on, along the future OLS developments.
