### ISSUE TITLE
Remove obsoleted ontologies?

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#402]
The page at https://www.ebi.ac.uk/ols/ontologies shows obsolete resources as if they were still valid. For example the first entry (AERO) is deprecated. I would suggest striking those out  and ordering them at the end (as is done in the [OBO table](http://www.obofoundry.org))

**Comment by udp** [comment]
Thanks, this is a good idea!  We will add it to the list for the next release.

**Comment by udp** [comment]
OLS is actually configured so that any ontology marked as obsolete by OBO is not loaded at all. The only reason we still have AERO and similar in OLS is because we loaded them before they were marked as obsolete. So, we can either keep these existing obsolete ontologies in OLS but mark them as obsolete, or remove them from OLS entirely.

The ontologies in question are:

aero
bcgo
dinto
eo
mirnao
emap
epo
flu
sep

**Comment by matentzn** [comment]
Please remove! We should not encourage annotating to obsolete ontologies!

**Comment by mcourtot** [comment]
I agree with @matentzn (even though I use to develop AERO and will still feel sad ;)) 

I would suggest removing from public display/table/search. I'm not sure about what to do for the loading aspect though, some of those may rely on OLS for dereferencing, and if not loaded will return 404. Maybe check the OBO configuration and make sure they don't use OLS by default first?

**Comment by henrietteharmse** [comment]
@matentzn @mcourtot Yes, I agree very much with deleting the obsolete ontologies.

@mcourtot OLS loading skips over any ontologies that are marked as obsolete. OBO config does not have any other references to these ontologoes
