### ISSUE TITLE
foaf depiction not working again

### ISSUE THREAD

**Issue by srobb1** [EBISPOT/OLS#437]
Hello,

The depition by isn't working again, #419 

There is an icon, but no image.

![Screen Shot 2020-11-02 at 10 37 16 AM](https://user-images.githubusercontent.com/1072991/97900130-7cba0e00-1cf7-11eb-8c35-5b3db9ac9366.png)

Thank you,
Sofia

**Comment by henrietteharmse** [comment]
I have just checked it now and as far as I can see it is working. Can you please provide the exact URL and/or steps you have taken when you encountered the error?

![image](https://user-images.githubusercontent.com/32327979/97962873-f57ba180-1dad-11eb-88b8-e27dc0eab0a1.png)

**Comment by srobb1** [comment]
Here is the URL I am using on my Mac in chrome `https://www.ebi.ac.uk/ols/ontologies/plana/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPLANA_0000418`. Also two of my colleagues are having the same issue with the depiction. Two of us are on macs the other on windows. But!!!! it does work on my phone! What the heck?!

**Comment by srobb1** [comment]
It works on Safari. Not Chrome.

**Comment by henrietteharmse** [comment]
Thanks for pointing that out. So checking this again I can confirm it working in Firefox as well, but not in Chrome.

**Comment by udp** [comment]
The problem is that:

1. The URL in the depiction property is `http://purl.obolibrary.org/obo/plana/images/head.png`
2. Chrome's security policy enforces https because OLS is accessed over HTTPS. So, `https://purl.obolibrary.org/obo/plana/images/head.png` is requested instead.
3. Requests to `https://purl.obolibrary.org/obo/plana/images/head.png` time out. Try for example `curl https://purl.obolibrary.org/obo/plana/images/head.png`: `curl: (7) Failed to connect to purl.obolibrary.org port 443: Operation timed out`

So I think there is a problem with https access to `https://purl.obolibrary.org/` which is not an issue with OLS. Not sure who to contact about this?

**Comment by matentzn** [comment]
Ok I checked with OBO foundry and @jamesaoverton and the OBO purl system does not currently support https. @srobb1 you will have to code the links to the images using the github https URLs unfortunately! There is nothing that can be done on the OLS side. You could make a ticket here: 

https://github.com/OBOFoundry/purl.obolibrary.org/issues

And ask for HTTPS support!

**Comment by srobb1** [comment]
Thank you. I have my depiction pointing to raw github links. This is working now. I created an issue on purl.obolibrary to see if they will consider supporting https.

Thank you for everyone's help to figure this out.
Sofia
