### ISSUE TITLE
link to ontology.dev.data.humancellatlas.org

### ISSUE THREAD

**Issue by lcdaugherty** [EBISPOT/OLS#443]
Hi
I used to be able to access the dev site, but the link no longer works https://ontology.dev.data.humancellatlas.org/ontologies/mondo
Has it been retired/replaced with something else?
Thanks

**Comment by matentzn** [comment]
Does this work for you in the meantime:
https://www.ebi.ac.uk/ols/ontologies/mondo

?

**Comment by lcdaugherty** [comment]
@matentzn Yes that does of course work, but there seemed to be additional info/comments/data on the dev site that I found useful.
Will dev site access return to the public domain again?

**Comment by matentzn** [comment]
Not sure that's the right advice (@zoependlington @dosumis could you double-check?), but maybe this is a better place for a ticket of this kind: https://github.com/HumanCellAtlas

Does anyone know who is responsible for the HCA ols deployment?

As am aside: what useful information/comments/data was displayed there? Maybe that would be useful in general?

**Comment by matentzn** [comment]
cc @rdgoite

**Comment by rdgoite** [comment]
Unfortunately, I'm no longer in the HCA team, so I don't know what happened to the original URL. @ebi-ait/hca-dev can probably help you with this.

**Comment by lauraclarke** [comment]
The correct link to use now is https://ontology.dev.archive.data.humancellatlas.org/ontologies/mondo

We had to change the URL due to some changes in the back end infrastructure

This version of OLS is an internal service. If you are either just querying OLS or building anything on top of OLS you are better to use the official service which can be found as @matentzn said on https://www.ebi.ac.uk/ols/ontologies/mondo

thanks
