### ISSUE TITLE
isDefiningOntology API endpoint for HSapDv terms

### ISSUE THREAD

**Issue by mshadbolt** [EBISPOT/OLS#476]
Hi

Not sure if this is the best place to post an issue but I am getting an error when searching some terms in the ols by the isDefiningOntology API endpoint eg.:

http://www.ebi.ac.uk/ols/api/terms/findByIdAndIsDefiningOntology?iri=http://purl.obolibrary.org/obo/HsapDv_0000081

http://www.ebi.ac.uk/ols/api/terms/findByIdAndIsDefiningOntology?iri=http://purl.obolibrary.org/obo/HsapDv_0000086

Is this something that can be fixed or a suggested work around to be able to choose the source ontology from an obo_id ?

Thanks!

**Comment by henrietteharmse** [comment]
Hey there Marion, 
We try to investigate this shortly. Thanks for reporting it.

**Comment by dosumis** [comment]
Hi Marion - can you provide some more context about why this is needed?  In particular why a call to the main OLS API?  Thanks!

**Comment by mshadbolt** [comment]
I found a work around so you can close this if it isn't expected that these endpoints should always resolve.

**Comment by henrietteharmse** [comment]
The reason why this does not work on the main OLS is because the base URIs for HCAO is configured differently from what it is on the HCA OLS instance.

OLS main instance:
```
    base_uri:
      - http://ontology.data.humancellatlas.org/ontologies/HCA_
```

OLS HCA instance:
```
    base_uri:
      - http://ontology.data.humancellatlas.org/ontologies/HCA_
      - http://purl.obolibrary.org/obo/UBERON_
      - http://purl.obolibrary.org/obo/CL_
      - http://purl.obolibrary.org/obo/HsapDv_
```

We do have a different config on OLS main? As an example, on the main OLS we have UBERON as an ontology for which ideally users want `isDefiningOntology` to return UBERON rather than UBERON **and** HCAO.
