### ISSUE TITLE
Protein Ontology not updated

### ISSUE THREAD

**Issue by nataled** [EBISPOT/OLS#530]
On this page https://www.ebi.ac.uk/ols/ontologies/pr the version indicated is v64.0. The current version, however, is v65.0, which became available on 2021-12-17. According to your documentation, there should have been a download either that evening or the next day (the FAQ indicates a nightly update). I see that the last load was performed on 2021-12-15, which would indeed have grabbed v64.0 (the penultimate release). Can the release be updated for PR? This issue was reported to us by an OLS user. 

In case this happens again, I'd like to be able to report back to a user what your load frequency is (or, more properly, what your checking frequency is). Is it actually nightly?

**Comment by udp** [comment]
Hi, our data releases are currently frozen for the holiday period as there will be no staff present to debug if there is an issue. The next data release will be on 3rd January, and nightly thereafter.

**Comment by udp** [comment]
Normally, they run each night from Sunday to Thursday, so that if there is a failure it will be during a work day. However, sometimes the data release takes more than 24 hours so we have to skip the following night. The speed of the indexing process is one of the main priorities for the next version of OLS, for this reason.

**Comment by nataled** [comment]
Thank you so much for the prompt response! This makes sense. As my question was answered, and as nothing appears to be otherwise amiss (that is, the update cycle isn't actually broken), I'm closing this ticket.
