### ISSUE TITLE
Display of individuals

### ISSUE THREAD

**Issue by sonata82** [EBISPOT/OLS#63]
It seems that OLS not yet displays individuals from an ontology, although they can be imported and queried using the API. 

I would like to add a visual component to allow the user to see individuals and have two ideas for this:

1. Show the individuals next to the tree, in the same fashion as class relations: ![individuals](https://cloud.githubusercontent.com/assets/454269/13673764/d7aae238-e6da-11e5-97a8-47f5e899059d.png)
2. Add an additional tab, next to ´Term metadata´

What are your thoughts?

**Comment by LLTommy** [comment]
Hey, 
my thoughts on this: Individuals have an own page - just like properties and terms (even though they looks very similar). So if you go to the advanced search, you can chose in the type field between term, property and individual. Searching for a random individual, you will see the individual is the 'term view' and the tab next to it changed to "Individual metadata". On your screenshot, I see the tab 'Term metadata' so you are on a term page and not on an 'Individual page' - just something I want to point out because you are obviously developing in your local environment. 

Besides that, we can always talk about making the user interface better - we are thankful for suggestions.

**Comment by sonata82** [comment]
Thanks for your quick reply! Yes, you are totally right, displaying the metadata from an individual is also possible.

But I'm also interested in giving the user the opportunity to discover the ontology by going through the tree view. On the individual page, the tree however does not display the other individuals, even when clicking on ´show siblings´:
![individuals_2](https://cloud.githubusercontent.com/assets/454269/13698073/038587ea-e772-11e5-90ce-572ddf92bf0b.png)
That's maybe just a bug?

Is there any other way in switching to the individuals page, besides using the advanced search?

**Comment by simonjupp** [comment]
I think it's reasonable to have a link to show instances of a particular
class on the class page. We're making a few changes to the term view layout
at the moment and will incorporate your suggestion.

Thanks

**Comment by sonata82** [comment]
Sounds great, thanks! 

If you guys need any extra manpower for implementing this, I'd be happy to step in.

**Comment by cmungall** [comment]
Was this ever implemented?

When I follow the individual URI from a class (e.g. "Illumina" from here):
https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0002002

I end up at:

https://www.ebi.ac.uk/ols/ontologies/obi/individuals?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000759

which is a 500

**Comment by simonjupp** [comment]
Yes, you can see instances of a class e.g. https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000098&viewMode=All&siblings=false. 

Seems other individuals are showing up fine for OBI. We'll look into it.
