### ISSUE TITLE
PCL OLS page doesn't seem to load

### ISSUE THREAD

**Issue by shawntanzk** [EBISPOT/OLS#639]
Trying to load https://www.ebi.ac.uk/ols/ontologies/pcl results in a long wait time then: 
![Screenshot 2022-09-27 at 11 17 45](https://user-images.githubusercontent.com/76212760/192500312-b7bedd0f-2feb-4dd0-9c9a-180c22ee3535.png)
PCL terms do however load perfectly fine (e.g. http://purl.obolibrary.org/obo/PCL_0011193 works perfectly fine) 
No rush as I think most people (at least I do) access it by term than ontology, but just reporting it here :) 

Thanks!

**Comment by serjoshua** [comment]
Hi Shawn,

We're on it. We deployed some data updates to production earlier and you might have just accessed a restarting server. Let us verify first. We'll get back to you as soon as we can.

**Comment by serjoshua** [comment]
Hello Shawn, I accessed and checked all our prod instances and they seem to run fine. Let us know if you still experience the server error when accessing PCL or OLS in general. And yes, some ontologies, including PCL, take some time to load. In this case, the server error might have been caused by one of the prod instances restarting.

**Comment by shawntanzk** [comment]
Works well now, thanks @serjoshua

**Comment by serjoshua** [comment]
No worries. Thanks for reporting!
