### ISSUE TITLE
Adding new Foundry ontology T4FS to OLS

### ISSUE THREAD

**Issue by allysonlister** [EBISPOT/OLS#643]
Good morning all!

[terms4FAIRskills](https://obofoundry.org/ontology/t4fs) has just been added to the OBO Foundry :-)

Please can you let me know the procedure for integrating it with OLS? I'd love to be able to point people to OLS to browse the ontology.

Thanks!

**Comment by serjoshua** [comment]
Hi Allyson,

Thank you for letting us know and upon checking it is indeed in OBO's configuration already. As of the moment, OLS is not doing regular updates. The earliest scheduled release we have is on the 18th, exactly next week. We will keep you posted regarding the deployment and we will surely include T4FS in it.

**Comment by allysonlister** [comment]
That's lovely - thank you so much, I'll take a look next week.
Thanks again!

**Comment by allysonlister** [comment]
Good morning! Just checked https://www.ebi.ac.uk/ols/ontologies/t4fs and haven't seen anything. For reference when should I expect it to appear please?

Thanks again!

**Comment by serjoshua** [comment]
Good morning Allyson,

Apologies for giving you the impression it will be available today. We indeed kicked off the deployment yesterday and it is in progress. Updates will be available tomorrow at the latest. We will keep you posted, especially if we encountered any issues or the like.

**Comment by allysonlister** [comment]
No need to apologise! Just good to know, and thanks!

**Comment by serjoshua** [comment]
Hello Allyson,

This is just an FYI. So, I am testing our pre-prod environment as of the moment and I cannot seem to find your ontology at first, but then I tried searching it using the title and it worked. Apparently, the `preferredPrefix` is set TF4S and I was searching T4FS. Not sure if it is a discrepancy but it gave me a mini-heart attack earlier if I'm being honest :) If it really is a discrepancy, I just want to mention that any updates on your side since (start of deployment) yesterday might not be picked up until the next data release, which could be a little far off.

**Comment by allysonlister** [comment]
Oh dear - some kind of capitalisation issue - I'll check all the relevant markdown files. Thanks!

**Comment by allysonlister** [comment]
As you can see from the github notification above, I have submitted a PR. Hopefully you can still index t4fs even with preferredPrefix not being as expected.

(even if this seems to show that I cannot spell "preferred" :-) )

**Comment by serjoshua** [comment]
No worries. It's all good on our side with regards to the data release so far. The `preferredPrefix` has affected the UI but as you can see in the URL, it didn't affect the API cos it still uses the ontology `id` instead of the `preferredPrefix`. Hopefully, that will be the only issue.

![Screen Shot 2022-10-19 at 2 19 49 PM](https://user-images.githubusercontent.com/25520595/196703943-9146ce85-a475-4763-8e49-f4bd0d204576.png)

![Screen Shot 2022-10-19 at 2 18 41 PM](https://user-images.githubusercontent.com/25520595/196703989-cf26686c-9228-44c0-b82c-83e5af681b99.png)

**Comment by jamesaoverton** [comment]
I think that the problem is not capitalization, it's the order of the "4" and "F" characters ("T4FS" vs "TF4s"). Right?

**Comment by serjoshua** [comment]
It is. I checked the PR and it was corrected anyway. Once deployment is done, hopefully, it won't be too much of a bother working with the current `preferredPrefix`. My only worry right now are the APIs, but it seems like the APIs are using ontology `id`.

**Comment by allysonlister** [comment]
The PR has been updated such that `preferredPrefix: T4FS` - I've been told we should keep it all capitalised. Hopefully my typo will not cause any more problems!

**Comment by serjoshua** [comment]
Good day Allyson and James,

T4FS has finally been added to OLS but with the problematic prefix. Feel free to create tickets for any issues encountered in OLS or urgent updates you want to be deployed to production. Thank you so much and regards.

**Comment by allysonlister** [comment]
No worries - thank you so much!

**Comment by serjoshua** [comment]
T4FS has just been updated in OLS with the new preferred prefix. FYI. Thanks!

**Comment by allysonlister** [comment]
That's great thank you!
