### ISSUE TITLE
Delay in OLS picking up latest version of VBO

### ISSUE THREAD

**Issue by franknic** [EBISPOT/OLS#651]
A new version of Vertebrate Breed Ontology (VBO) was released on 2022-10-31 [(https://github.com/monarch-initiative/vertebrate-breed-ontology),](url) but has not yet been picked up at [https://www.ebi.ac.uk/ols/ontologies/vbo](url). Since the aim is for a new release of VBO at the end of each month, OLS is in danger of falling seriously behind.
I and my colleagues are very grateful for the services provided by EBI OLS, and we fully understand that delays can occur. The purpose of this message is simply to bring this delay to your notice.
frank.nicholas@sydney.edu.au

**Comment by henrietteharmse** [comment]
Thanks for bringing this to our attention. We will ensure VBO will be added to our list of ontologies to update in the data release scheduled to run 16 Dec with availability of the update around 21 Dec. 

As you correctly observe, there are delays in the OLS data releases. This is an inevitable side effect of our data releases taking ever longer to run and has become rather unstable and less than predictable to the point that it threatens the availability of OLS. 

To deal with this the team is working incredibly hard to:
1. Ensure the availability of OLS. In the last months we had a number of releases where the databases got corrupted and it was only due to efforts of the team that we were able to keep OLS up. 
2. We are rewriting OLS to address the stability issues and to enable much quicker (hours rather than weeks) turnaround times for updating the indexes (exactly the concern you raised in this issue).

We are glad you find the service useful and we appreciate your understanding for our efforts in this regard.

**Comment by serjoshua** [comment]
Hello Frank,

We included VBO in our release today. It is now updated in OLS. If you encounter any discrepancies, feel free to message us. Regards.

**Comment by franknic** [comment]
Thank you very much!!
